### ISSUE TITLE
move all the things!

### ISSUE THREAD

**Issue by kevinkreiser** [valhalla/tools#1]
we want to put path_test, city_test, adjacency_list_benchmark, skadi_benchmark, loki_benchmark, time_distance_test tools/tests into this repo.

first step autotools scaffold. second step, move all the source.

**Comment by kevinkreiser** [comment]
ill do the autotools fun, @dgearhart can have the code motion ;)

**Comment by dgearhart** [comment]
moved over the path test scripts and route request files into new directory structure
re factored to work in new directory structure
added documentation for scripts
