### ISSUE TITLE
make python bindings optional

### ISSUE THREAD

**Issue by kevinkreiser** [valhalla/tools#121]
its annoying to have to have python to build tools. so we should be able to turn it off if desired. this should just require some autotools configure magic and probably mess with the packaging stuff (until the mono repo)

@noblige @zerebubuth

**Comment by noblige** [comment]
Can we make this also not depend on mjolnir?

**Comment by kevinkreiser** [comment]
@noblige we could do that, but if we end up doing the mono repo (i hope we do) everything will be in one place and there will be no need for it. do you mind if we hold off until we decide on the single repo or not. i figure we'll have that decided in a few days? @dnesbitt61 what do you think?

**Comment by dnesbitt61** [comment]
Yes, if @noblige can override this locally for now (valhalla_associate_segments is only code that relies on mjolnir) we can plan/decide on the course of action for the single repo early next week.

**Comment by noblige** [comment]
I think we should separate components that are required to run valhalla and components needed to build maps. This is important when you think cross-compiling, as I don't need `mjolnir` for example, nor any other tools really besides `valhalla_route_service` and `valhalla_run_route` compiled for target.

By separate, I mean `configure` flags or something like that, so even with single repo I can pick/choose what to build for host/target.

**Comment by kevinkreiser** [comment]
@noblige yeah thats a good point, we should probably have configure options to turn on or off data building stuff so that places where you dont need it you can avoid having to build it. this will be good for mobile as well. thanks for pointing this out!
