### ISSUE TITLE
valhalla_run_route -j ''   -> get output as json with route geom

### ISSUE THREAD

**Issue by KlemenSpruk** [valhalla/tools#125]
Hello!

Is it possible to get result of valhalla_run_route -j '!{}'  command as json with route geometry?

Thank Klemen !

**Comment by dnesbitt61** [comment]
Not with valhalla_run_route. However, you can run the service locally within the tools directory (point to the same conf file you would with valhalla_run_route:

./valhalla_route_service ../conf/valhalla.json

Then use curl or a browser window to send the JSON request to the local server (localhost:8002/route) and you will get a JSON response with the route geometry. The route geometry is an encoded polyline.

**Comment by KlemenSpruk** [comment]
OK, then it is possible via running server. Thanks!
