### ISSUE TITLE
valhalla_build_tiles task missing

### ISSUE THREAD

**Issue by shashanktomar** [valhalla/tools#58]
I folks, i am trying to build valahalla modules as per instructions given [here](https://github.com/valhalla/tools#building-and-running-valhalla). Build is going through but no binary with name "valhalla_build_tiles" is generated. Is the name changed for this task or am i missing something?

**Comment by gknisely** [comment]
valhalla_build_tiles is under mjolnir.  Did it build correctly?

--Greg.

**Comment by shashanktomar** [comment]
Digging deeper into the log revealed mjolnir's ```make -j$(nproc)``` is failing with error. ```make: *** No rule to make target `src/proto/osmformat.pb.cc', needed by `install'.  Stop.```

**Comment by shashanktomar** [comment]
Checked out the older [commit](https://github.com/valhalla/mjolnir/commit/a31cfda3dbec89ba136cd12e2457ea82e5056704) fixed it for me. Looks like the build failure after today's changed caused the issue.

**Comment by kevinkreiser** [comment]
the osmformat stuff is all submodules. make sure you do `git submodule init` and `git submodule update` just in case or you can `git clone --recurvsive` to avoid having to do the submodules manually
