### ISSUE TITLE
build fail (dependency check)

### ISSUE THREAD

**Issue by glennon** [valhalla/tools#71]
FYI - Using the instructions to build Valhalla from the README.md (using Ubuntu Trusty) yields the error below. I used the README instructions after a similar error appeared while building using ./build.sh from the https://github.com/valhalla/valhalla-docker repo. Prior, I've successfully built a Docker image using that method within the last week. Since that valhalla-docker repo is forked from elsewhere, it does not contain a tab to report Issues.

As a side note, building in Ubuntu 16.04 Xenial likely would fail even quicker, as libboost1.54-all-dev would need to be updated across Valhalla's various dependent repos to .58 (or .61?). 

-------------------------------
error building manually from instructions in README.md:  

```
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for VALHALLA_DEPS... no
configure: error: Package requirements (libvalhalla_midgard = unstable libvalhalla_baldr = unstable libvalhalla_odin = unstable) were not met:

No package 'libvalhalla_odin' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables VALHALLA_DEPS_CFLAGS
and VALHALLA_DEPS_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
make: *** No targets specified and no makefile found.  Stop.
make: *** No rule to make target `install'.  Stop.
/
```

--------------------------------------
error using ./build.sh from valhalla-docker repo:  

```
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for VALHALLA_DEPS... no
configure: error: Package requirements (libvalhalla_midgard = unstable libvalhalla_baldr = unstable libvalhalla_meili = unstable libvalhalla_sif = unstable libvalhalla_odin = unstable) were not met:

No package 'libvalhalla_meili' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables VALHALLA_DEPS_CFLAGS
and VALHALLA_DEPS_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
```

**Comment by kevinkreiser** [comment]
Should be fixed now. Forgot to add meindl@lvc.edu to tools when we made it a dep for thor

**Comment by glennon** [comment]
Thanks @kevinkreiser. 
- [x] <b>Success</b> building with valhalla-docker repo's ./build.sh 
- [ ] <b>Testing Underway</b> Manual build with instructions from valhalla/tools README.md
